services:
  nl2sql-service:
    build:
      context: .
    
    env_file:
      - .env

    restart: unless-stopped

    command: >
      bash -c "
        cd src &&
        python -m schema_linking.evaluation.evaluate_pruning
      "